package com.projecteden.collection.service;

import java.time.Clock;import java.time.LocalDateTime;import java.util.List;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.projecteden.achievement.service.AchievementService;import com.projecteden.ai.domain.RecognizedObject;import com.projecteden.character.domain.Character;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.collection.domain.*;import com.projecteden.collection.dto.*;import com.projecteden.collection.repository.CollectionRepository;import com.projecteden.common.exception.ResourceNotFoundException;import com.projecteden.statistics.service.StatisticsService;
@Service public class CollectionService{
	private final CollectionRepository collections;private final CharacterRepository characters;private final StatisticsService statistics;private final AchievementService achievements;private final Clock clock;
	public CollectionService(CollectionRepository collections,CharacterRepository characters,StatisticsService statistics,AchievementService achievements,Clock clock){this.collections=collections;this.characters=characters;this.statistics=statistics;this.achievements=achievements;this.clock=clock;}
	@Transactional public CollectionResponse registerDiscovery(Long characterId,RecognizedObject object){if(object==null)throw new IllegalArgumentException("인식 대상은 필수입니다.");Character c=characters.findById(characterId).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));LocalDateTime now=LocalDateTime.now(clock);Collection value=collections.findByCharacterIdAndRecognizedObject(characterId,object).map(existing->{existing.rediscover(now);return existing;}).orElseGet(()->collections.save(Collection.create(c,object,rarity(object),now)));statistics.refreshStatistics(characterId);achievements.evaluateAchievements(characterId);return response(value);}
	@Transactional(readOnly=true) public CollectionSummaryResponse getMyCollectionSummary(Long userId){Character c=characters.findByUserId(userId).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));List<CollectionResponse> values=collections.findByCharacterId(c.getId()).stream().map(this::response).toList();int total=RecognizedObject.values().length;return new CollectionSummaryResponse(total,values.size(),values.size()*100.0/total,values);}
	private Rarity rarity(RecognizedObject object){return object==RecognizedObject.UNKNOWN?Rarity.UNCOMMON:Rarity.COMMON;}private CollectionResponse response(Collection c){return new CollectionResponse(c.getId(),c.getRecognizedObject(),c.getRarity(),c.getDiscoveredCount(),c.getFirstDiscoveredAt(),c.getLastDiscoveredAt());}
}
