package com.projecteden.title.service;

import java.time.Clock;import java.time.LocalDateTime;import java.util.List;import java.util.Map;import java.util.function.Function;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.projecteden.character.domain.Character;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.common.exception.ResourceNotFoundException;import com.projecteden.statistics.service.StatisticsService;import com.projecteden.title.domain.*;import com.projecteden.title.dto.TitleResponse;import com.projecteden.title.repository.*;
@Service public class TitleService{
	private final TitleRepository titles;private final UserTitleRepository userTitles;private final CharacterRepository characters;private final StatisticsService statistics;private final Clock clock;
	public TitleService(TitleRepository titles,UserTitleRepository userTitles,CharacterRepository characters,StatisticsService statistics,Clock clock){this.titles=titles;this.userTitles=userTitles;this.characters=characters;this.statistics=statistics;this.clock=clock;}
	@Transactional public UserTitle grantTitle(Long characterId,String titleCode){return userTitles.findByCharacterIdAndTitleCode(characterId,titleCode).orElseGet(()->{Character c=character(characterId);Title t=titles.findByCode(titleCode).orElseThrow(()->new ResourceNotFoundException("칭호를 찾을 수 없습니다."));UserTitle granted=userTitles.save(UserTitle.create(c,t,LocalDateTime.now(clock)));statistics.refreshStatistics(characterId);return granted;});}
	@Transactional(readOnly=true) public List<TitleResponse> getMyTitles(Long userId){Character c=byUser(userId);Map<String,UserTitle> acquired=userTitles.findByCharacterId(c.getId()).stream().collect(Collectors.toMap(v->v.getTitle().getCode(),Function.identity()));return titles.findAll().stream().map(t->{UserTitle u=acquired.get(t.getCode());return new TitleResponse(t.getCode(),t.getName(),t.getDescription(),u!=null,u!=null&&u.isActive(),u==null?null:u.getAcquiredAt());}).toList();}
	@Transactional public TitleResponse setActiveTitle(Long userId,String titleCode){Character c=byUser(userId);UserTitle target=userTitles.findByCharacterIdAndTitleCode(c.getId(),titleCode).orElseThrow(()->new IllegalArgumentException("보유하지 않은 칭호입니다."));userTitles.findByCharacterIdAndActiveTrue(c.getId()).ifPresent(UserTitle::deactivate);target.activate();Title t=target.getTitle();return new TitleResponse(t.getCode(),t.getName(),t.getDescription(),true,true,target.getAcquiredAt());}
	private Character byUser(Long id){return characters.findByUserId(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}private Character character(Long id){return characters.findById(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}
}
