package com.projecteden.vision;

public enum VisionRuntimeErrorCode {
	RUNTIME_UNAVAILABLE,
	NATIVE_LIBRARY_LOAD_FAILED,
	MODEL_PATH_MISSING,
	MODEL_FILE_NOT_FOUND,
	MODEL_CHECKSUM_MISMATCH,
	MODEL_LOAD_FAILED,
	MODEL_METADATA_INVALID,
	OUTPUT_CONTRACT_MISMATCH,
	INPUT_SHAPE_INVALID,
	PREPROCESSING_FAILED,
	INFERENCE_FAILED,
	OUTPUT_SHAPE_INVALID,
	NON_FINITE_OUTPUT,
	RESOURCE_CLOSE_FAILED,
	UNSUPPORTED_PLATFORM
}
