package com.projecteden.village.domain;
public enum VillageChangeType { TABLE, BAKERY, CAFE, HERB_GARDEN, FLOWER_PATH, GARDEN, FOREST_PATH, VIEWPOINT, WALKING_PATH, BENCH, PARK, SIGNPOST, SMALL_BRIDGE, HARBOR, WATERSIDE_PATH, LIGHTHOUSE, CAT_SPOT, BIRD_NEST, DOG_WALK_PATH, SMALL_SHELTER, QUIET_PLACE }
