package com.projecteden.visit.service;
import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.projecteden.character.repository.CharacterRepository; import com.projecteden.common.exception.ResourceNotFoundException; import com.projecteden.friend.service.FriendService; import com.projecteden.profile.repository.ProfileRepository; import com.projecteden.user.domain.User; import com.projecteden.user.repository.UserRepository; import com.projecteden.visit.domain.IslandVisit; import com.projecteden.visit.dto.VisitResponseDTO; import com.projecteden.visit.repository.IslandVisitRepository; import com.projecteden.world.repository.WorldRepository;
@Service public class IslandVisitService {
	private final IslandVisitRepository visits; private final UserRepository users; private final FriendService friends; private final CharacterRepository characters; private final WorldRepository worlds; private final ProfileRepository profiles;
	public IslandVisitService(IslandVisitRepository visits,UserRepository users,FriendService friends,CharacterRepository characters,WorldRepository worlds,ProfileRepository profiles){this.visits=visits;this.users=users;this.friends=friends;this.characters=characters;this.worlds=worlds;this.profiles=profiles;}
	@Transactional public VisitResponseDTO visitIsland(Long userId,Long friendId){User visitor=user(userId),owner=user(friendId);if(!friends.areFriends(visitor,owner))throw new IllegalArgumentException("친구의 섬만 방문할 수 있습니다.");return response(visits.save(IslandVisit.create(visitor,owner)));}
	@Transactional(readOnly=true) public List<VisitResponseDTO> history(Long userId){return visits.findByVisitor(user(userId)).stream().map(this::response).toList();}
	private VisitResponseDTO response(IslandVisit v){var c=characters.findByUserId(v.getOwner().getId()).orElse(null);var w=c==null?null:worlds.findByCharacterId(c.getId()).orElse(null);var p=profiles.findByUser(v.getOwner()).orElse(null);return new VisitResponseDTO(v.getId(),v.getOwner().getId(),v.getOwner().getNickname(),w==null?null:w.getWorldName(),w==null?"SPRING":w.getSeason().name(),p==null?null:p.getRepresentativeCreature(),p==null?null:p.getRepresentativeIsland(),v.getVisitedAt());}
	private User user(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("사용자를 찾을 수 없습니다."));}
}
