package com.projecteden.village;

import static org.hamcrest.Matchers.hasItem;import static org.junit.jupiter.api.Assertions.assertEquals;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;
import com.projecteden.ai.domain.RecognizedObject;import com.projecteden.ai.repository.RecognitionRepository;import com.projecteden.ai.service.RecognitionApplicationService;import com.projecteden.auth.jwt.JwtTokenProvider;import com.projecteden.character.domain.Character;import com.projecteden.character.domain.CharacterGender;import com.projecteden.character.domain.CharacterJob;import com.projecteden.character.domain.HairStyle;import com.projecteden.character.domain.Outfit;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.evolution.repository.*;import com.projecteden.photo.domain.Photo;import com.projecteden.photo.repository.PhotoRepository;import com.projecteden.user.domain.User;import com.projecteden.user.repository.UserRepository;import com.projecteden.village.domain.*;import com.projecteden.village.repository.*;import com.projecteden.village.service.VillageService;

@SpringBootTest@AutoConfigureMockMvc@ActiveProfiles("test")class VillageIntegrationTests{
	@Autowired MockMvc mockMvc;@Autowired VillageService service;@Autowired VillageMemoryRepository memories;@Autowired VillageChangeRepository changes;@Autowired VillageHistoryRepository histories;@Autowired VillageThemeSnapshotRepository themeSnapshots;@Autowired RecognitionApplicationService recognitionService;@Autowired RecognitionRepository recognitions;@Autowired PhotoRepository photos;@Autowired EvolutionHistoryRepository evolutionHistories;@Autowired WorldDecorationRepository decorations;@Autowired WorldEvolutionRepository evolutions;@Autowired CharacterRepository characters;@Autowired UserRepository users;@Autowired PasswordEncoder encoder;@Autowired JwtTokenProvider tokens;
	private User user;private Character character;private String token;
	@BeforeEach void setUp(){clean();user=users.save(new User("village@example.com",encoder.encode("password123"),"villager"));character=characters.save(Character.create(user,"마을사람",CharacterGender.NONE,HairStyle.PIXEL_CUT,"brown",Outfit.ROBE,CharacterJob.WIZARD));token=tokens.generateAccessToken(user);}@AfterEach void tearDown(){clean();}

	@Test void firstVillageIsEmpty(){var village=service.getMyVillage(character.getId());assertEquals(VillageCategory.UNKNOWN,village.dominantCategory());assertEquals(0,village.totalMemoryCount());assertEquals("아직 마을은 조용히 당신의 첫 순간을 기다리고 있습니다.",village.latestMessage());}
	@Test void flowerRecognitionCreatesNatureMemory(){Photo photo=photo();recognitionService.recognizePhoto(user.getId(),photo.getId());assertMemory(VillageCategory.NATURE,1);}
	@Test void tomatoCreatesFoodMemory(){service.recordVillageMemory(character.getId(),RecognizedObject.TOMATO);assertMemory(VillageCategory.FOOD,1);}
	@Test void unknownCreatesUnknownMemory(){service.recordVillageMemory(character.getId(),RecognizedObject.UNKNOWN);assertMemory(VillageCategory.UNKNOWN,1);}
	@Test void repeatedCategoryIncreasesCount(){service.recordVillageMemory(character.getId(),RecognizedObject.TOMATO);service.recordVillageMemory(character.getId(),RecognizedObject.CARROT);assertMemory(VillageCategory.FOOD,2);}
	@Test void firstNatureMemoryCreatesFlowerPath(){record(RecognizedObject.FLOWER,1);assertChange(VillageChangeType.FLOWER_PATH);}
	@Test void fifthNatureMemoryCreatesGarden(){record(RecognizedObject.FLOWER,5);assertChange(VillageChangeType.GARDEN);}
	@Test void firstFoodMemoryCreatesTable(){record(RecognizedObject.TOMATO,1);assertChange(VillageChangeType.TABLE);}
	@Test void firstUnknownMemoryCreatesQuietPlace(){record(RecognizedObject.UNKNOWN,1);assertChange(VillageChangeType.QUIET_PLACE);}
	@Test void sameChangeIsNotDuplicated(){record(RecognizedObject.FLOWER,2);assertEquals(1,changes.findByCharacterId(character.getId()).stream().filter(value->value.getChangeType()==VillageChangeType.FLOWER_PATH).count());}
	@Test void memoryRecordedHistoryIsSaved(){record(RecognizedObject.FLOWER,1);assertHistory(VillageHistoryType.MEMORY_RECORDED);}
	@Test void changeAppearedHistoryIsSaved(){record(RecognizedObject.FLOWER,1);assertHistory(VillageHistoryType.CHANGE_APPEARED);}
	@Test void npcReactionHistoryIsSaved(){record(RecognizedObject.FLOWER,1);assertHistory(VillageHistoryType.NPC_REACTION);}
	@Test void villageApiSucceeds()throws Exception{record(RecognizedObject.FLOWER,1);mockMvc.perform(get("/api/village/me").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(jsonPath("$.dominantCategory").value("NATURE")).andExpect(jsonPath("$.latestMessage").value("꽃이 참 많이 피는 계절이네요."));}
	@Test void historyApiSucceeds()throws Exception{record(RecognizedObject.FLOWER,1);mockMvc.perform(get("/api/village/history").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(jsonPath("$[*].historyType",hasItem("NPC_REACTION")));}
	@Test void historyApiReturnsOnlyTheAuthenticatedUsersHistory()throws Exception{record(RecognizedObject.FLOWER,1);User other=users.save(new User("village-other@example.com",encoder.encode("password123"),"other-villager"));Character otherCharacter=characters.save(Character.create(other,"다른마을",CharacterGender.NONE,HairStyle.PIXEL_CUT,"black",Outfit.ROBE,CharacterJob.WIZARD));service.recordVillageMemory(otherCharacter.getId(),RecognizedObject.DOG);mockMvc.perform(get("/api/village/history").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(jsonPath("$[*].category",hasItem("NATURE"))).andExpect(jsonPath("$[*].category",org.hamcrest.Matchers.not(hasItem("ANIMAL"))));}
	@Test void changesApiSucceeds()throws Exception{record(RecognizedObject.FLOWER,1);mockMvc.perform(get("/api/village/changes").header("Authorization",bearer())).andExpect(status().isOk()).andExpect(jsonPath("$[0].changeType").value("FLOWER_PATH"));}
	@Test void apiRequiresJwt()throws Exception{mockMvc.perform(get("/api/village/me")).andExpect(status().isUnauthorized());}

	private Photo photo(){String stored=UUID.randomUUID()+".jpg";return photos.save(Photo.create(character,null,"flower.jpg",stored,"image/jpeg",10,"/uploads/photos/"+stored));}private void record(RecognizedObject object,int count){for(int i=0;i<count;i++)service.recordVillageMemory(character.getId(),object);}private void assertMemory(VillageCategory category,int count){assertEquals(count,memories.findByCharacterIdAndCategory(character.getId(),category).orElseThrow().getMemoryCount());}private void assertChange(VillageChangeType type){assertEquals(true,changes.existsByCharacterIdAndChangeType(character.getId(),type));}private void assertHistory(VillageHistoryType type){assertEquals(true,histories.findByCharacterIdOrderByCreatedAtDesc(character.getId()).stream().anyMatch(value->value.getHistoryType()==type));}private String bearer(){return "Bearer "+token;}
	private void clean(){histories.deleteAll();changes.deleteAll();themeSnapshots.deleteAll();memories.deleteAll();evolutionHistories.deleteAll();decorations.deleteAll();evolutions.deleteAll();recognitions.deleteAll();photos.deleteAll();characters.deleteAll();users.deleteAll();}
}
