package com.projecteden.vision.eden;

public enum EdenObjectCode {
	PERSON, CAT, DOG, BIRD, HORSE, SHEEP, COW,
	WILD_ANIMAL, FARM_ANIMAL,
	BOOK, LAPTOP, KEYBOARD, MOUSE, MONITOR, PHONE,
	CUP, BOTTLE, BOWL, FORK, KNIFE, SPOON,
	FRUIT, VEGETABLE, PLANT,
	CHAIR, COUCH, BED, TABLE,
	BICYCLE, MOTORCYCLE, CAR, BUS, TRAIN,
	VEHICLE, OUTDOOR, BAG, SPORT, KITCHEN, TOY, CLOTHING, BUILDING,
	TEDDY_BEAR, OTHER_OBJECT,
	UNKNOWN_OBJECT
}
