package com.projecteden.vision.eden;

public enum EdenObjectFamily {
	HUMAN, ANIMAL, PET, WILD_ANIMAL, FARM_ANIMAL, LEARNING_TOOL, DIGITAL_DEVICE,
	FOOD_AND_DRINK, VEGETABLE, PLANT, FURNITURE, TRANSPORT, OUTDOOR,
	BAG, SPORT, KITCHEN, TOY, CLOTHING, BUILDING, OTHER
}
