package com.projecteden.village.service;

import java.time.Clock;import java.time.LocalDateTime;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.projecteden.ai.domain.RecognizedObject;import com.projecteden.character.domain.Character;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.common.exception.ResourceNotFoundException;import com.projecteden.village.domain.*;import com.projecteden.village.dto.*;import com.projecteden.village.repository.*;
@Service public class VillageService{
	private static final String EMPTY_MESSAGE="아직 마을은 조용히 당신의 첫 순간을 기다리고 있습니다.";
	private final VillageMemoryRepository memories;private final VillageChangeRepository changes;private final VillageHistoryRepository histories;private final CharacterRepository characters;private final Clock clock;private final VillageInterpretationService interpretations;
	public VillageService(VillageMemoryRepository memories,VillageChangeRepository changes,VillageHistoryRepository histories,CharacterRepository characters,Clock clock,VillageInterpretationService interpretations){this.memories=memories;this.changes=changes;this.histories=histories;this.characters=characters;this.clock=clock;this.interpretations=interpretations;}
	@Transactional public VillageResponse recordVillageMemory(Long characterId,RecognizedObject object){if(object==null)throw new IllegalArgumentException("마을이 기억할 대상이 필요합니다.");Character character=character(characterId);VillageCategory category=categoryFor(object);LocalDateTime now=LocalDateTime.now(clock);VillageMemory memory=memories.findByCharacterIdAndCategory(characterId,category).map(value->{value.record(now);return value;}).orElseGet(()->memories.save(VillageMemory.create(character,category,now)));history(character,VillageHistoryType.MEMORY_RECORDED,category,null,"마을에 "+category.name().toLowerCase()+"의 흔적이 조용히 머물렀습니다.",now);interpretations.interpretAndUpdateTheme(characterId);String reaction=reactionFor(category);for(ChangeRule rule:rulesFor(category)){if(memory.getMemoryCount()>=rule.count()&&!changes.existsByCharacterIdAndChangeType(characterId,rule.type())){changes.save(VillageChange.appear(character,category,rule.type(),now));history(character,VillageHistoryType.CHANGE_APPEARED,category,rule.type(),reaction,now);}}history(character,VillageHistoryType.NPC_REACTION,category,null,reaction,now);return village(characterId,reaction);}
	@Transactional(readOnly=true) public VillageResponse getMyVillage(Long characterId){character(characterId);String latest=histories.findTopByCharacterIdOrderByIdDesc(characterId).map(VillageHistory::getMessage).orElse(EMPTY_MESSAGE);return village(characterId,latest);}
	@Transactional(readOnly=true) public List<VillageHistoryResponse> getMyVillageHistory(Long characterId){character(characterId);return histories.findByCharacterIdOrderByCreatedAtDesc(characterId).stream().map(h->new VillageHistoryResponse(h.getHistoryType(),h.getCategory(),h.getChangeType(),h.getMessage(),h.getCreatedAt())).toList();}
	@Transactional(readOnly=true) public List<VillageChangeResponse> getMyVillageChanges(Long characterId){character(characterId);return changes.findByCharacterId(characterId).stream().map(this::changeResponse).toList();}
	@Transactional(readOnly=true) public VillageResponse getVillageByUserId(Long userId){return getMyVillage(byUser(userId).getId());}@Transactional(readOnly=true) public List<VillageHistoryResponse> getHistoryByUserId(Long userId){return getMyVillageHistory(byUser(userId).getId());}@Transactional(readOnly=true) public List<VillageChangeResponse> getChangesByUserId(Long userId){return getMyVillageChanges(byUser(userId).getId());}
	private VillageResponse village(Long characterId,String latest){List<VillageMemoryResponse> memoryResponses=memories.findByCharacterId(characterId).stream().map(m->new VillageMemoryResponse(m.getCategory(),m.getMemoryCount(),m.getLastRecordedAt())).toList();long total=memoryResponses.stream().mapToLong(VillageMemoryResponse::memoryCount).sum();VillageCategory dominant=memoryResponses.stream().sorted(Comparator.comparingInt(VillageMemoryResponse::memoryCount).reversed().thenComparing(value->value.category().ordinal())).map(VillageMemoryResponse::category).findFirst().orElse(VillageCategory.UNKNOWN);return new VillageResponse(dominant,total,memoryResponses,getMyVillageChanges(characterId),latest);}
	private VillageChangeResponse changeResponse(VillageChange change){return new VillageChangeResponse(change.getCategory(),change.getChangeType(),change.isAppeared(),change.getAppearedAt(),reactionFor(change.getCategory()));}
	private VillageCategory categoryFor(RecognizedObject object){return object.getCategory();}
	private List<ChangeRule> rulesFor(VillageCategory category){return switch(category){case FOOD->List.of(new ChangeRule(1,VillageChangeType.TABLE),new ChangeRule(5,VillageChangeType.HERB_GARDEN),new ChangeRule(10,VillageChangeType.BAKERY),new ChangeRule(20,VillageChangeType.CAFE));case NATURE->List.of(new ChangeRule(1,VillageChangeType.FLOWER_PATH),new ChangeRule(5,VillageChangeType.GARDEN),new ChangeRule(10,VillageChangeType.FOREST_PATH),new ChangeRule(20,VillageChangeType.VIEWPOINT));case WALK->List.of(new ChangeRule(1,VillageChangeType.WALKING_PATH),new ChangeRule(5,VillageChangeType.SIGNPOST),new ChangeRule(10,VillageChangeType.BENCH),new ChangeRule(20,VillageChangeType.PARK));case WATER->List.of(new ChangeRule(1,VillageChangeType.WATERSIDE_PATH),new ChangeRule(5,VillageChangeType.SMALL_BRIDGE),new ChangeRule(10,VillageChangeType.HARBOR),new ChangeRule(20,VillageChangeType.LIGHTHOUSE));case ANIMAL->List.of(new ChangeRule(1,VillageChangeType.SMALL_SHELTER),new ChangeRule(5,VillageChangeType.BIRD_NEST),new ChangeRule(10,VillageChangeType.CAT_SPOT),new ChangeRule(20,VillageChangeType.DOG_WALK_PATH));case STUDY,WORK,UNKNOWN->List.of(new ChangeRule(1,VillageChangeType.QUIET_PLACE));};}
	private String reactionFor(VillageCategory category){return switch(category){case FOOD->"따뜻한 식탁이 하나 더 늘어난 것 같네요.";case NATURE->"꽃이 참 많이 피는 계절이네요.";case WALK->"작은 산책길이 마을에 머물기 시작했습니다.";case WATER->"물가에 조용한 길이 생겼습니다.";case ANIMAL->"새들이 머무를 작은 자리가 생겼습니다.";case STUDY->"조용히 쌓인 시간이 마을의 한편에 머물기 시작했습니다.";case WORK->"오늘의 노력이 작은 불빛이 되어 남았습니다.";case UNKNOWN->"마을이 조용히 오늘의 순간을 간직했습니다.";};}
	private void history(Character character,VillageHistoryType type,VillageCategory category,VillageChangeType change,String message,LocalDateTime now){histories.save(VillageHistory.create(character,type,category,change,message,now));}private Character character(Long id){return characters.findById(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}private Character byUser(Long id){return characters.findByUserId(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}private record ChangeRule(int count,VillageChangeType type){}
}
