package com.projecteden.npcmemory.dialogue;

public enum NpcDialogueKey {
	FIRST_MEETING,

	BLOOMING_FIRST,
	BLOOMING_RETURNING,
	BLOOMING_REPEAT_ALT,

	WARM_FIRST,
	WARM_RETURNING,
	WARM_REPEAT_ALT,

	WALKING_FIRST,
	WALKING_RETURNING,
	WALKING_REPEAT_ALT,

	WATERSIDE_FIRST,
	WATERSIDE_RETURNING,
	WATERSIDE_REPEAT_ALT,

	ANIMAL_FIRST,
	ANIMAL_RETURNING,
	ANIMAL_REPEAT_ALT,

	QUIET_FIRST,
	QUIET_RETURNING,
	QUIET_REPEAT_ALT,

	UNDEFINED_FIRST,
	UNDEFINED_RETURNING,

	RECENT_THEME_CHANGE,
	RECENT_MEMORY_RECORDED,
	RECENT_CHANGE_APPEARED
}
