package com.projecteden.imagenormalization;

public enum ImageNormalizationErrorCode {
	EMPTY_INPUT,
	ENCODED_SIZE_EXCEEDED,
	UNSUPPORTED_FORMAT,
	SIGNATURE_MISMATCH,
	DECODER_UNAVAILABLE,
	CORRUPTED_IMAGE,
	DIMENSION_EXCEEDED,
	PIXEL_LIMIT_EXCEEDED,
	FRAME_LIMIT_EXCEEDED,
	ORIENTATION_FAILED,
	COLOR_CONVERSION_FAILED,
	RESIZE_FAILED,
	ENCODING_FAILED,
	OUTPUT_SIZE_EXCEEDED,
	NORMALIZATION_FAILED
}
