package com.projecteden.world.ecology;

public enum WorldAssetType {
    FLOWER_CLUSTER, TREE_GROVE, POND, VISITOR, WATER_VISITOR, MIXED_VISITOR,
    STORYBOOK_RESIDENT, BAKERY_DETAIL, CAFE_DETAIL, LIBRARY_DETAIL, ROAD_DETAIL,
    ATMOSPHERE, MEMORY_SPARK,
    PLAZA, FARM_PLOT_EMPTY, FARM_CARROT, FARM_FLOWER, FARM_VEGETABLE, FARM_TOMATO, FARM_CABBAGE,
    COMMUNITY_HOUSE, BUSH, DEFAULT_NPC_GUIDE, DEFAULT_NPC_GARDENER,
    DEFAULT_NPC_MEMORY_KEEPER, DEFAULT_NPC_ANIMAL_CARETAKER,
    DEFAULT_DOG, DEFAULT_CAT, DEFAULT_BIRD
}
