package com.projecteden.evolution.service;

import java.time.Clock;import java.time.LocalDateTime;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.projecteden.character.domain.Character;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.common.exception.ResourceNotFoundException;import com.projecteden.evolution.domain.*;import com.projecteden.evolution.dto.*;import com.projecteden.evolution.repository.*;
@Service public class EvolutionService{
	private final WorldEvolutionRepository evolutions;private final WorldDecorationRepository decorations;private final EvolutionHistoryRepository histories;private final CharacterRepository characters;private final Clock clock;
	public EvolutionService(WorldEvolutionRepository evolutions,WorldDecorationRepository decorations,EvolutionHistoryRepository histories,CharacterRepository characters,Clock clock){this.evolutions=evolutions;this.decorations=decorations;this.histories=histories;this.characters=characters;this.clock=clock;}
	@Transactional public WorldEvolution getOrCreateEvolution(Long characterId){return evolutions.findByCharacterId(characterId).orElseGet(()->evolutions.save(WorldEvolution.create(character(characterId))));}
	@Transactional public WorldEvolutionResponse addEvolutionPoint(Long characterId,EvolutionSourceType sourceType){if(sourceType==null)throw new IllegalArgumentException("성장 포인트 출처는 필수입니다.");Character character=character(characterId);WorldEvolution evolution=getOrCreateEvolution(characterId);int point=pointFor(sourceType),oldLevel=evolution.getWorldLevel();WorldStage oldStage=evolution.getWorldStage();evolution.addPoint(point);history(character,EvolutionEventType.POINT_GAIN,sourceType+" 활동으로 EP "+point+"을 획득했습니다.");int newLevel=levelFor(evolution.getEvolutionPoint());WorldStage newStage=stageFor(newLevel);if(newLevel>oldLevel)history(character,EvolutionEventType.LEVEL_UP,"월드 레벨이 "+oldLevel+"에서 "+newLevel+"로 상승했습니다.");if(newStage!=oldStage)history(character,EvolutionEventType.STAGE_UP,"월드 단계가 "+oldStage+"에서 "+newStage+"로 성장했습니다.");evolution.evolve(newLevel,newStage);unlockDecorations(character,newLevel);return response(evolution);}
	@Transactional public WorldEvolutionResponse getMyEvolution(Long characterId){return response(getOrCreateEvolution(characterId));}
	@Transactional(readOnly=true) public List<WorldDecorationResponse> getMyDecorations(Long characterId){character(characterId);return decorations.findByCharacterId(characterId).stream().map(d->new WorldDecorationResponse(d.getDecorationType(),d.isUnlocked(),d.getUnlockedAt())).toList();}
	@Transactional(readOnly=true) public List<EvolutionHistoryResponse> getMyHistory(Long characterId){character(characterId);return histories.findByCharacterIdOrderByCreatedAtDesc(characterId).stream().map(h->new EvolutionHistoryResponse(h.getEventType(),h.getDescription(),h.getCreatedAt())).toList();}
	@Transactional public WorldEvolutionResponse getEvolutionByUserId(Long userId){return getMyEvolution(byUser(userId).getId());}@Transactional(readOnly=true) public List<WorldDecorationResponse> getDecorationsByUserId(Long userId){return getMyDecorations(byUser(userId).getId());}@Transactional(readOnly=true) public List<EvolutionHistoryResponse> getHistoryByUserId(Long userId){return getMyHistory(byUser(userId).getId());}
	private void unlockDecorations(Character character,int level){for(DecorationType type:decorationTypesFor(level)){if(!decorations.existsByCharacterIdAndDecorationType(character.getId(),type)){decorations.save(WorldDecoration.unlock(character,type,LocalDateTime.now(clock)));history(character,EvolutionEventType.DECORATION_UNLOCK,type+" 장식이 해금되었습니다.");}}}
	private List<DecorationType> decorationTypesFor(int level){List<DecorationType> types=new ArrayList<>();if(level>=2)types.add(DecorationType.FLOWER_FIELD);if(level>=3)types.add(DecorationType.TREE);if(level>=4)types.addAll(List.of(DecorationType.BENCH,DecorationType.ROAD));if(level>=5)types.addAll(List.of(DecorationType.LAMP,DecorationType.FOUNTAIN,DecorationType.WINDMILL));return types;}
	private int pointFor(EvolutionSourceType source){return switch(source){case RECOGNITION->5;case RESONANCE->10;case ACHIEVEMENT->30;case CHEER->2;};}private int levelFor(int point){if(point>=1000)return 5;if(point>=500)return 4;if(point>=250)return 3;if(point>=100)return 2;return 1;}private WorldStage stageFor(int level){return WorldStage.values()[level-1];}private int nextPoint(int level){return switch(level){case 1->100;case 2->250;case 3->500;default->1000;};}
	private void history(Character c,EvolutionEventType type,String description){histories.save(EvolutionHistory.create(c,type,description,LocalDateTime.now(clock)));}private WorldEvolutionResponse response(WorldEvolution e){int next=nextPoint(e.getWorldLevel());double rate=Math.min(100.0,e.getEvolutionPoint()*100.0/next);return new WorldEvolutionResponse(e.getWorldLevel(),e.getEvolutionPoint(),e.getWorldStage(),next,rate);}private Character character(Long id){return characters.findById(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}private Character byUser(Long id){return characters.findByUserId(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}
}
