package com.projecteden.achievement.service;

import java.time.Clock;import java.time.LocalDateTime;import java.util.List;import java.util.Map;import java.util.function.Function;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.projecteden.achievement.domain.*;import com.projecteden.achievement.dto.AchievementResponse;import com.projecteden.achievement.repository.*;import com.projecteden.character.domain.Character;import com.projecteden.character.repository.CharacterRepository;import com.projecteden.collection.repository.CollectionRepository;import com.projecteden.common.exception.ResourceNotFoundException;import com.projecteden.statistics.service.StatisticsService;import com.projecteden.title.service.TitleService;
@Service public class AchievementService{
	private final AchievementRepository achievements;private final UserAchievementRepository userAchievements;private final CollectionRepository collections;private final CharacterRepository characters;private final TitleService titles;private final StatisticsService statistics;private final Clock clock;
	public AchievementService(AchievementRepository achievements,UserAchievementRepository userAchievements,CollectionRepository collections,CharacterRepository characters,TitleService titles,StatisticsService statistics,Clock clock){this.achievements=achievements;this.userAchievements=userAchievements;this.collections=collections;this.characters=characters;this.titles=titles;this.statistics=statistics;this.clock=clock;}
	@Transactional public void evaluateAchievements(Long characterId){Character c=character(characterId);long unique=collections.countByCharacterId(characterId),total=collections.sumDiscoveredCountByCharacterId(characterId);int max=collections.maxDiscoveredCountByCharacterId(characterId);for(Achievement a:achievements.findAll()){if(!userAchievements.existsByCharacterIdAndAchievementCode(characterId,a.getCode())&&qualifies(a,unique,total,max)){userAchievements.save(UserAchievement.create(c,a,LocalDateTime.now(clock)));if(a.getRewardTitleCode()!=null)titles.grantTitle(characterId,a.getRewardTitleCode());}}statistics.refreshStatistics(characterId);}
	@Transactional(readOnly=true) public List<AchievementResponse> getMyAchievements(Long userId){Character c=byUser(userId);Map<String,UserAchievement> achieved=userAchievements.findByCharacterId(c.getId()).stream().collect(Collectors.toMap(v->v.getAchievement().getCode(),Function.identity()));return achievements.findAll().stream().map(a->{UserAchievement u=achieved.get(a.getCode());return new AchievementResponse(a.getCode(),a.getName(),a.getDescription(),a.getType(),a.getRequiredValue(),u!=null,u==null?null:u.getAchievedAt(),a.getRewardTitleCode());}).toList();}
	private boolean qualifies(Achievement a,long unique,long total,int max){return switch(a.getType()){case FIRST_DISCOVERY->total>=1;case COLLECTION_COUNT->unique>=a.getRequiredValue();case TOTAL_DISCOVERY_COUNT->total>=a.getRequiredValue();case SAME_OBJECT_COUNT->max>=a.getRequiredValue();};}
	private Character byUser(Long id){return characters.findByUserId(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}private Character character(Long id){return characters.findById(id).orElseThrow(()->new ResourceNotFoundException("캐릭터를 찾을 수 없습니다."));}
}
