--
-- PostgreSQL database dump
--
-- Flyway baseline migration for a brand-new PostgreSQL schema.
--
-- V1-V9 remain the immutable upgrade lineage for databases that already have
-- Flyway history. New databases select this B9 baseline, which captures the
-- schema after V9 without replaying V2's historical photos/recognitions
-- predecessor assumption. No application data or Flyway history is included.


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    required_value integer NOT NULL,
    reward_title_code character varying(255),
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT achievements_type_check CHECK (((type)::text = ANY ((ARRAY['FIRST_DISCOVERY'::character varying, 'COLLECTION_COUNT'::character varying, 'TOTAL_DISCOVERY_COUNT'::character varying, 'SAME_OBJECT_COUNT'::character varying])::text[])))
);


--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.character_statistics (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    last_discovery_at timestamp(6) without time zone,
    total_achievements bigint NOT NULL,
    total_discoveries bigint NOT NULL,
    total_titles bigint NOT NULL,
    unique_collections bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL
);


--
-- Name: character_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.character_statistics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.characters (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    energy integer NOT NULL,
    exp integer NOT NULL,
    gender character varying(255) NOT NULL,
    hair_color character varying(255) NOT NULL,
    hair_style character varying(255) NOT NULL,
    job character varying(255) NOT NULL,
    level integer NOT NULL,
    name character varying(255) NOT NULL,
    outfit character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    weapon_type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT characters_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT characters_hair_style_check CHECK (((hair_style)::text = ANY ((ARRAY['SHORT'::character varying, 'LONG'::character varying, 'WAVY'::character varying, 'PONYTAIL'::character varying, 'BALD'::character varying, 'PIXEL_CUT'::character varying])::text[]))),
    CONSTRAINT characters_job_check CHECK (((job)::text = ANY ((ARRAY['BEGINNER'::character varying, 'FARMER'::character varying, 'EXPLORER'::character varying, 'GUARDIAN'::character varying, 'MERCHANT'::character varying, 'BREEDER'::character varying, 'WIZARD'::character varying, 'WARRIOR'::character varying, 'ARCHER'::character varying, 'BUILDER'::character varying])::text[]))),
    CONSTRAINT characters_outfit_check CHECK (((outfit)::text = ANY ((ARRAY['BASIC'::character varying, 'FARMER'::character varying, 'ADVENTURER'::character varying, 'ROBE'::character varying, 'ARMOR'::character varying, 'ANIMAL_KEEPER'::character varying])::text[]))),
    CONSTRAINT characters_weapon_type_check CHECK (((weapon_type)::text = ANY ((ARRAY['NONE'::character varying, 'HOE'::character varying, 'COMPASS'::character varying, 'SHIELD'::character varying, 'BAG'::character varying, 'FEED_BASKET'::character varying, 'STAFF'::character varying, 'SWORD'::character varying, 'BOW'::character varying, 'HAMMER'::character varying])::text[])))
);


--
-- Name: characters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.characters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.characters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cheers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cheers (
    id bigint NOT NULL,
    cheered_at timestamp(6) without time zone,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


--
-- Name: cheers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cheers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cheers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    discovered_count integer NOT NULL,
    first_discovered_at timestamp(6) without time zone NOT NULL,
    last_discovered_at timestamp(6) without time zone NOT NULL,
    rarity character varying(255) NOT NULL,
    recognized_object character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT collections_rarity_check CHECK (((rarity)::text = ANY ((ARRAY['COMMON'::character varying, 'UNCOMMON'::character varying, 'RARE'::character varying, 'EPIC'::character varying, 'LEGENDARY'::character varying])::text[]))),
    CONSTRAINT collections_recognized_object_check CHECK (((recognized_object)::text = ANY ((ARRAY['FLOWER'::character varying, 'TOMATO'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'WHEAT'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_missions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_missions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    harvest_completed boolean NOT NULL,
    mission_date date NOT NULL,
    photo_completed boolean NOT NULL,
    plant_completed boolean NOT NULL,
    reward_claimed boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL
);


--
-- Name: daily_missions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_missions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_missions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_penalties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_penalties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    missed_days integer NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: daily_penalties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_penalties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_penalties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evolution_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evolution_histories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    character_id bigint NOT NULL,
    CONSTRAINT evolution_histories_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['POINT_GAIN'::character varying, 'LEVEL_UP'::character varying, 'STAGE_UP'::character varying, 'DECORATION_UNLOCK'::character varying])::text[])))
);


--
-- Name: evolution_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evolution_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evolution_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friends (
    id bigint NOT NULL,
    accepted_at timestamp(6) without time zone,
    requested_at timestamp(6) without time zone,
    status character varying(255),
    receiver_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    CONSTRAINT friends_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying])::text[])))
);


--
-- Name: friends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.friends ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: houses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.houses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    house_name character varying(255) NOT NULL,
    house_type character varying(255) NOT NULL,
    level integer NOT NULL,
    max_decoration integer NOT NULL,
    updated_at timestamp(6) without time zone,
    world_id bigint NOT NULL,
    CONSTRAINT houses_house_type_check CHECK (((house_type)::text = ANY ((ARRAY['CABIN'::character varying, 'WOODEN'::character varying, 'STONE'::character varying, 'CASTLE'::character varying])::text[])))
);


--
-- Name: houses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.houses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.houses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventories (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    used_slot integer NOT NULL,
    house_id bigint NOT NULL
);


--
-- Name: inventories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: island_visits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.island_visits (
    id bigint NOT NULL,
    visited_at timestamp(6) without time zone,
    owner_id bigint NOT NULL,
    visitor_id bigint NOT NULL
);


--
-- Name: island_visits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.island_visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.island_visits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memory_classification_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_classification_categories (
    id bigint NOT NULL,
    confidence numeric(5,4),
    created_at timestamp(6) without time zone NOT NULL,
    role character varying(30) NOT NULL,
    category_id bigint NOT NULL,
    classification_id bigint NOT NULL,
    CONSTRAINT memory_classification_categories_role_check CHECK (((role)::text = ANY ((ARRAY['PRIMARY'::character varying, 'SECONDARY'::character varying])::text[])))
);


--
-- Name: memory_classification_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memory_classification_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memory_classification_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memory_classification_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_classification_tags (
    id bigint NOT NULL,
    confidence numeric(5,4),
    created_at timestamp(6) without time zone NOT NULL,
    classification_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: memory_classification_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memory_classification_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memory_classification_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memory_classifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_classifications (
    id bigint NOT NULL,
    confidence numeric(5,4),
    created_at timestamp(6) without time zone NOT NULL,
    fallback boolean NOT NULL,
    model_version character varying(100),
    observation jsonb,
    provider character varying(40) NOT NULL,
    summary character varying(500),
    taxonomy_version character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    photo_id bigint NOT NULL,
    primary_category_id bigint,
    recognition_id bigint
);


--
-- Name: memory_classifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memory_classifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memory_classifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memory_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_tags (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(80) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(100) NOT NULL,
    tag_type character varying(40) NOT NULL,
    taxonomy_version character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT memory_tags_tag_type_check CHECK (((tag_type)::text = ANY ((ARRAY['SUBJECT'::character varying, 'SCENE'::character varying, 'ACTIVITY'::character varying, 'MOOD'::character varying, 'RELATIONSHIP'::character varying, 'OBJECT'::character varying])::text[])))
);


--
-- Name: memory_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memory_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memory_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memory_taxonomy_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_taxonomy_categories (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category_type character varying(40) NOT NULL,
    code character varying(80) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    taxonomy_version character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    parent_id bigint,
    CONSTRAINT memory_taxonomy_categories_category_type_check CHECK (((category_type)::text = ANY ((ARRAY['DOMAIN'::character varying, 'ACTIVITY'::character varying, 'RELATIONSHIP'::character varying, 'PLACE'::character varying, 'MOOD'::character varying])::text[])))
);


--
-- Name: memory_taxonomy_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memory_taxonomy_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memory_taxonomy_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    is_read boolean NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['DAILY_PROMPT'::character varying, 'CHEER_RECEIVED'::character varying, 'SEASON_CHANGE'::character varying, 'FRIEND_ADDED'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: npc_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npc_memories (
    id bigint NOT NULL,
    character_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    interaction_count integer NOT NULL,
    last_dialogue_key character varying(255),
    last_interacted_at timestamp(6) without time zone,
    npc_id bigint NOT NULL,
    remembered_category character varying(255),
    remembered_theme character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT npc_memories_remembered_category_check CHECK (((remembered_category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT npc_memories_remembered_theme_check CHECK (((remembered_theme)::text = ANY ((ARRAY['BLOOMING_VILLAGE'::character varying, 'WARM_VILLAGE'::character varying, 'WALKING_VILLAGE'::character varying, 'WATERSIDE_VILLAGE'::character varying, 'ANIMAL_FRIENDLY_VILLAGE'::character varying, 'QUIET_VILLAGE'::character varying, 'UNDEFINED'::character varying])::text[])))
);


--
-- Name: npc_memories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.npc_memories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.npc_memories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: npcs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.npcs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    npc_name character varying(255) NOT NULL,
    npc_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    region_id bigint NOT NULL,
    CONSTRAINT npcs_npc_type_check CHECK (((npc_type)::text = ANY ((ARRAY['VILLAGE_CHIEF'::character varying, 'GARDENER'::character varying, 'CARPENTER'::character varying, 'MERCHANT'::character varying, 'ARCHIVIST'::character varying])::text[])))
);


--
-- Name: npcs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.npcs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.npcs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.photos (
    id bigint NOT NULL,
    content_type character varying(255),
    created_at timestamp(6) without time zone,
    file_size bigint NOT NULL,
    image_url character varying(255) NOT NULL,
    original_file_name character varying(255) NOT NULL,
    stored_file_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uploaded_at timestamp(6) without time zone NOT NULL,
    character_id bigint NOT NULL,
    plant_id bigint
);


--
-- Name: photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    last_growth_checked_at timestamp(6) without time zone NOT NULL,
    plant_stage character varying(255) NOT NULL,
    planted_at timestamp(6) without time zone NOT NULL,
    resonance_boosted boolean NOT NULL,
    seed_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    region_id bigint NOT NULL,
    CONSTRAINT plants_plant_stage_check CHECK (((plant_stage)::text = ANY ((ARRAY['SEED'::character varying, 'SPROUT'::character varying, 'GROWING'::character varying, 'BLOOMED'::character varying, 'WITHERED'::character varying])::text[]))),
    CONSTRAINT plants_seed_type_check CHECK (((seed_type)::text = ANY ((ARRAY['WHEAT'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'TOMATO'::character varying, 'FLOWER'::character varying])::text[])))
);


--
-- Name: plants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    user_id bigint NOT NULL,
    avatar_url character varying(255),
    current_season character varying(255),
    join_date date NOT NULL,
    representative_creature character varying(255),
    representative_island character varying(255),
    total_play_days integer NOT NULL
);


--
-- Name: rankings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rankings (
    user_id bigint NOT NULL,
    consecutive_logins integer NOT NULL,
    season_achievements integer NOT NULL,
    total_play_days integer NOT NULL
);


--
-- Name: recognitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recognitions (
    id bigint NOT NULL,
    confidence integer NOT NULL,
    created_at timestamp(6) without time zone,
    recognized boolean NOT NULL,
    recognized_object character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    photo_id bigint NOT NULL,
    planting_target_object_id bigint,
    CONSTRAINT recognitions_recognized_object_check CHECK (((recognized_object)::text = ANY ((ARRAY['FLOWER'::character varying, 'TREE'::character varying, 'PLANT'::character varying, 'SKY'::character varying, 'LANDSCAPE'::character varying, 'CAT'::character varying, 'DOG'::character varying, 'BIRD'::character varying, 'ANIMAL'::character varying, 'FOOD'::character varying, 'BREAD'::character varying, 'FRUIT'::character varying, 'VEGETABLE'::character varying, 'TOMATO'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'WHEAT'::character varying, 'WATER'::character varying, 'RIVER'::character varying, 'SEA'::character varying, 'POND'::character varying, 'ROAD'::character varying, 'PATH'::character varying, 'PARK'::character varying, 'STREET'::character varying, 'BOOK'::character varying, 'NOTEBOOK'::character varying, 'STUDY'::character varying, 'READING'::character varying, 'LECTURE'::character varying, 'WRITING'::character varying, 'LIBRARY'::character varying, 'LAPTOP'::character varying, 'COMPUTER'::character varying, 'CODING'::character varying, 'PROGRAMMING'::character varying, 'DESK'::character varying, 'OFFICE'::character varying, 'MEETING'::character varying, 'WORKSPACE'::character varying, 'COFFEE'::character varying, 'ROOM'::character varying, 'DAILY_OBJECT'::character varying, 'PERSON'::character varying, 'FRIEND'::character varying, 'FAMILY'::character varying, 'OBJECT'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: recognitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recognitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recognitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.regions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    display_name character varying(255) NOT NULL,
    region_type character varying(255) NOT NULL,
    unlocked boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    world_id bigint NOT NULL,
    CONSTRAINT regions_region_type_check CHECK (((region_type)::text = ANY ((ARRAY['VILLAGE'::character varying, 'FOREST'::character varying, 'RIVER'::character varying, 'HILL'::character varying, 'FLOWER_FIELD'::character varying])::text[])))
);


--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resonances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resonances (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    recognized_object character varying(255) NOT NULL,
    resonance_date date NOT NULL,
    reward_gold integer NOT NULL,
    reward_seed_quantity integer NOT NULL,
    reward_seed_type character varying(255),
    reward_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    recognition_id bigint NOT NULL,
    CONSTRAINT resonances_recognized_object_check CHECK (((recognized_object)::text = ANY ((ARRAY['FLOWER'::character varying, 'TOMATO'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'WHEAT'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT resonances_reward_seed_type_check CHECK (((reward_seed_type)::text = ANY ((ARRAY['WHEAT'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'TOMATO'::character varying, 'FLOWER'::character varying])::text[]))),
    CONSTRAINT resonances_reward_type_check CHECK (((reward_type)::text = ANY ((ARRAY['SEED'::character varying, 'GOLD'::character varying, 'NONE'::character varying])::text[])))
);


--
-- Name: resonances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resonances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resonances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seeds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seeds (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    seed_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    inventory_id bigint NOT NULL,
    CONSTRAINT seeds_seed_type_check CHECK (((seed_type)::text = ANY ((ARRAY['WHEAT'::character varying, 'CARROT'::character varying, 'POTATO'::character varying, 'TOMATO'::character varying, 'FLOWER'::character varying])::text[])))
);


--
-- Name: seeds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seeds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seeds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: titles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.titles (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: titles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tutorial_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutorial_progress (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    current_step character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT tutorial_progress_current_step_check CHECK (((current_step)::text = ANY ((ARRAY['WELCOME'::character varying, 'MEET_CHIEF'::character varying, 'CHECK_HOME'::character varying, 'CHECK_INVENTORY'::character varying, 'VISIT_FLOWER_FIELD'::character varying, 'FINISHED'::character varying])::text[])))
);


--
-- Name: tutorial_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tutorial_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tutorial_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_achievements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_achievements (
    id bigint NOT NULL,
    achieved_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    achievement_id bigint NOT NULL,
    character_id bigint NOT NULL
);


--
-- Name: user_achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_titles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_titles (
    id bigint NOT NULL,
    acquired_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    title_id bigint NOT NULL
);


--
-- Name: user_titles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    last_login_at timestamp(6) without time zone,
    nickname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: village_changes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.village_changes (
    id bigint NOT NULL,
    appeared boolean NOT NULL,
    appeared_at timestamp(6) without time zone,
    category character varying(255) NOT NULL,
    change_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT village_changes_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT village_changes_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['TABLE'::character varying, 'BAKERY'::character varying, 'CAFE'::character varying, 'HERB_GARDEN'::character varying, 'FLOWER_PATH'::character varying, 'GARDEN'::character varying, 'FOREST_PATH'::character varying, 'VIEWPOINT'::character varying, 'WALKING_PATH'::character varying, 'BENCH'::character varying, 'PARK'::character varying, 'SIGNPOST'::character varying, 'SMALL_BRIDGE'::character varying, 'HARBOR'::character varying, 'WATERSIDE_PATH'::character varying, 'LIGHTHOUSE'::character varying, 'CAT_SPOT'::character varying, 'BIRD_NEST'::character varying, 'DOG_WALK_PATH'::character varying, 'SMALL_SHELTER'::character varying, 'QUIET_PLACE'::character varying])::text[])))
);


--
-- Name: village_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.village_changes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.village_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: village_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.village_histories (
    id bigint NOT NULL,
    category character varying(255),
    change_type character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    history_type character varying(255) NOT NULL,
    message character varying(255) NOT NULL,
    character_id bigint NOT NULL,
    CONSTRAINT village_histories_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT village_histories_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['TABLE'::character varying, 'BAKERY'::character varying, 'CAFE'::character varying, 'HERB_GARDEN'::character varying, 'FLOWER_PATH'::character varying, 'GARDEN'::character varying, 'FOREST_PATH'::character varying, 'VIEWPOINT'::character varying, 'WALKING_PATH'::character varying, 'BENCH'::character varying, 'PARK'::character varying, 'SIGNPOST'::character varying, 'SMALL_BRIDGE'::character varying, 'HARBOR'::character varying, 'WATERSIDE_PATH'::character varying, 'LIGHTHOUSE'::character varying, 'CAT_SPOT'::character varying, 'BIRD_NEST'::character varying, 'DOG_WALK_PATH'::character varying, 'SMALL_SHELTER'::character varying, 'QUIET_PLACE'::character varying])::text[]))),
    CONSTRAINT village_histories_history_type_check CHECK (((history_type)::text = ANY ((ARRAY['MEMORY_RECORDED'::character varying, 'CHANGE_APPEARED'::character varying, 'NPC_REACTION'::character varying, 'THEME_CHANGED'::character varying])::text[])))
);


--
-- Name: village_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.village_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.village_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: village_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.village_memories (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    last_recorded_at timestamp(6) without time zone NOT NULL,
    memory_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT village_memories_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: village_memories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.village_memories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.village_memories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: village_theme_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.village_theme_snapshots (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone,
    primary_category character varying(255),
    rule_version character varying(255) NOT NULL,
    secondary_category character varying(255),
    theme character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT village_theme_snapshots_primary_category_check CHECK (((primary_category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT village_theme_snapshots_secondary_category_check CHECK (((secondary_category)::text = ANY ((ARRAY['FOOD'::character varying, 'NATURE'::character varying, 'WALK'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT village_theme_snapshots_theme_check CHECK (((theme)::text = ANY ((ARRAY['BLOOMING_VILLAGE'::character varying, 'WARM_VILLAGE'::character varying, 'WALKING_VILLAGE'::character varying, 'WATERSIDE_VILLAGE'::character varying, 'ANIMAL_FRIENDLY_VILLAGE'::character varying, 'QUIET_VILLAGE'::character varying, 'UNDEFINED'::character varying])::text[])))
);


--
-- Name: village_theme_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.village_theme_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.village_theme_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_changes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_changes (
    id bigint NOT NULL,
    asset_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_message character varying(300) NOT NULL,
    focusx integer NOT NULL,
    focusy integer NOT NULL,
    message_key character varying(80) NOT NULL,
    world_category character varying(255) NOT NULL,
    character_id bigint NOT NULL,
    recognition_id bigint,
    target_object_id bigint,
    CONSTRAINT world_changes_asset_type_check CHECK (((asset_type)::text = ANY ((ARRAY['FLOWER_CLUSTER'::character varying, 'TREE_GROVE'::character varying, 'POND'::character varying, 'VISITOR'::character varying, 'WATER_VISITOR'::character varying, 'MIXED_VISITOR'::character varying, 'STORYBOOK_RESIDENT'::character varying, 'BAKERY_DETAIL'::character varying, 'CAFE_DETAIL'::character varying, 'LIBRARY_DETAIL'::character varying, 'ROAD_DETAIL'::character varying, 'ATMOSPHERE'::character varying, 'MEMORY_SPARK'::character varying, 'PLAZA'::character varying, 'FARM_PLOT_EMPTY'::character varying, 'FARM_CARROT'::character varying, 'FARM_FLOWER'::character varying, 'FARM_VEGETABLE'::character varying, 'FARM_TOMATO'::character varying, 'FARM_CABBAGE'::character varying, 'COMMUNITY_HOUSE'::character varying, 'BUSH'::character varying, 'DEFAULT_NPC_GUIDE'::character varying, 'DEFAULT_NPC_GARDENER'::character varying, 'DEFAULT_NPC_MEMORY_KEEPER'::character varying, 'DEFAULT_NPC_ANIMAL_CARETAKER'::character varying, 'DEFAULT_DOG'::character varying, 'DEFAULT_CAT'::character varying, 'DEFAULT_BIRD'::character varying])::text[]))),
    CONSTRAINT world_changes_target_crop_check CHECK (((target_object_id IS NULL) OR ((asset_type)::text = ANY ((ARRAY['FARM_CARROT'::character varying, 'FARM_FLOWER'::character varying, 'FARM_VEGETABLE'::character varying, 'FARM_TOMATO'::character varying, 'FARM_CABBAGE'::character varying])::text[])))),
    CONSTRAINT world_changes_world_category_check CHECK (((world_category)::text = ANY ((ARRAY['NATURE'::character varying, 'WATER'::character varying, 'ANIMAL'::character varying, 'AQUATIC_ANIMAL'::character varying, 'AMPHIBIOUS_ANIMAL'::character varying, 'TOY'::character varying, 'FOOD'::character varying, 'BUILDING'::character varying, 'TRANSPORT'::character varying, 'HOUSEHOLD'::character varying, 'SKY'::character varying, 'WEATHER'::character varying, 'MEMORY'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: world_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_changes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_decorations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_decorations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    decoration_type character varying(255) NOT NULL,
    unlocked boolean NOT NULL,
    unlocked_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    character_id bigint NOT NULL,
    CONSTRAINT world_decorations_decoration_type_check CHECK (((decoration_type)::text = ANY ((ARRAY['FLOWER_FIELD'::character varying, 'TREE'::character varying, 'BENCH'::character varying, 'ROAD'::character varying, 'LAMP'::character varying, 'FOUNTAIN'::character varying, 'WINDMILL'::character varying])::text[])))
);


--
-- Name: world_decorations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_decorations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_decorations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_evolutions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_evolutions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    evolution_point integer NOT NULL,
    updated_at timestamp(6) without time zone,
    world_level integer NOT NULL,
    world_stage character varying(255) NOT NULL,
    character_id bigint NOT NULL,
    CONSTRAINT world_evolutions_world_stage_check CHECK (((world_stage)::text = ANY ((ARRAY['SEED'::character varying, 'SPROUT'::character varying, 'GARDEN'::character varying, 'FOREST'::character varying, 'PARADISE'::character varying])::text[])))
);


--
-- Name: world_evolutions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_evolutions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_evolutions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_placed_objects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_placed_objects (
    id bigint NOT NULL,
    asset_type character varying(255) NOT NULL,
    habitat character varying(255) NOT NULL,
    positionx integer NOT NULL,
    positiony integer NOT NULL,
    terrain character varying(255) NOT NULL,
    world_change_id bigint NOT NULL,
    CONSTRAINT world_placed_objects_asset_type_check CHECK (((asset_type)::text = ANY ((ARRAY['FLOWER_CLUSTER'::character varying, 'TREE_GROVE'::character varying, 'POND'::character varying, 'VISITOR'::character varying, 'WATER_VISITOR'::character varying, 'MIXED_VISITOR'::character varying, 'STORYBOOK_RESIDENT'::character varying, 'BAKERY_DETAIL'::character varying, 'CAFE_DETAIL'::character varying, 'LIBRARY_DETAIL'::character varying, 'ROAD_DETAIL'::character varying, 'ATMOSPHERE'::character varying, 'MEMORY_SPARK'::character varying, 'PLAZA'::character varying, 'FARM_PLOT_EMPTY'::character varying, 'FARM_CARROT'::character varying, 'FARM_FLOWER'::character varying, 'FARM_VEGETABLE'::character varying, 'FARM_TOMATO'::character varying, 'FARM_CABBAGE'::character varying, 'COMMUNITY_HOUSE'::character varying, 'BUSH'::character varying, 'DEFAULT_NPC_GUIDE'::character varying, 'DEFAULT_NPC_GARDENER'::character varying, 'DEFAULT_NPC_MEMORY_KEEPER'::character varying, 'DEFAULT_NPC_ANIMAL_CARETAKER'::character varying, 'DEFAULT_DOG'::character varying, 'DEFAULT_CAT'::character varying, 'DEFAULT_BIRD'::character varying])::text[]))),
    CONSTRAINT world_placed_objects_habitat_check CHECK (((habitat)::text = ANY ((ARRAY['LAND'::character varying, 'WATER'::character varying, 'AMPHIBIOUS'::character varying, 'AIR'::character varying, 'DECORATION_ONLY'::character varying])::text[]))),
    CONSTRAINT world_placed_objects_terrain_check CHECK (((terrain)::text = ANY ((ARRAY['GRASS'::character varying, 'ROAD'::character varying, 'SOIL'::character varying, 'FLOWER_FIELD'::character varying, 'FOREST'::character varying, 'WATER'::character varying, 'BRIDGE'::character varying, 'BEACH'::character varying, 'BUILDING'::character varying, 'ROCK'::character varying, 'CLIFF'::character varying])::text[])))
);


--
-- Name: world_placed_objects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_placed_objects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_placed_objects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_player_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_player_positions (
    id bigint NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    character_id bigint NOT NULL
);


--
-- Name: world_player_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_player_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_player_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_terrain_tiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.world_terrain_tiles (
    id bigint NOT NULL,
    terrain_type character varying(255) NOT NULL,
    walkable boolean NOT NULL,
    tile_x integer NOT NULL,
    tile_y integer NOT NULL,
    character_id bigint NOT NULL,
    CONSTRAINT world_terrain_tiles_terrain_type_check CHECK (((terrain_type)::text = ANY ((ARRAY['GRASS'::character varying, 'ROAD'::character varying, 'SOIL'::character varying, 'FLOWER_FIELD'::character varying, 'FOREST'::character varying, 'WATER'::character varying, 'BRIDGE'::character varying, 'BEACH'::character varying, 'BUILDING'::character varying, 'ROCK'::character varying, 'CLIFF'::character varying])::text[])))
);


--
-- Name: world_terrain_tiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.world_terrain_tiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_terrain_tiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worlds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worlds (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    world_day integer NOT NULL,
    food integer NOT NULL,
    gold integer NOT NULL,
    season character varying(255) NOT NULL,
    seed bigint NOT NULL,
    stone integer NOT NULL,
    updated_at timestamp(6) without time zone,
    weather character varying(255) NOT NULL,
    wood integer NOT NULL,
    world_name character varying(255) NOT NULL,
    character_id bigint NOT NULL,
    village_template_version integer DEFAULT 0 NOT NULL,
    CONSTRAINT worlds_season_check CHECK (((season)::text = ANY ((ARRAY['SPRING'::character varying, 'SUMMER'::character varying, 'AUTUMN'::character varying, 'WINTER'::character varying])::text[]))),
    CONSTRAINT worlds_weather_check CHECK (((weather)::text = ANY ((ARRAY['SUNNY'::character varying, 'RAIN'::character varying, 'SNOW'::character varying, 'CLOUDY'::character varying])::text[])))
);


--
-- Name: worlds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.worlds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worlds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: character_statistics character_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.character_statistics
    ADD CONSTRAINT character_statistics_pkey PRIMARY KEY (id);


--
-- Name: characters characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (id);


--
-- Name: cheers cheers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cheers
    ADD CONSTRAINT cheers_pkey PRIMARY KEY (id);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: daily_missions daily_missions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_missions
    ADD CONSTRAINT daily_missions_pkey PRIMARY KEY (id);


--
-- Name: daily_penalties daily_penalties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_penalties
    ADD CONSTRAINT daily_penalties_pkey PRIMARY KEY (id);


--
-- Name: evolution_histories evolution_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evolution_histories
    ADD CONSTRAINT evolution_histories_pkey PRIMARY KEY (id);


--
-- Name: friends friends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT friends_pkey PRIMARY KEY (id);


--
-- Name: houses houses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT houses_pkey PRIMARY KEY (id);


--
-- Name: inventories inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_pkey PRIMARY KEY (id);


--
-- Name: island_visits island_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.island_visits
    ADD CONSTRAINT island_visits_pkey PRIMARY KEY (id);


--
-- Name: memory_classification_categories memory_classification_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_categories
    ADD CONSTRAINT memory_classification_categories_pkey PRIMARY KEY (id);


--
-- Name: memory_classification_tags memory_classification_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_tags
    ADD CONSTRAINT memory_classification_tags_pkey PRIMARY KEY (id);


--
-- Name: memory_classifications memory_classifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classifications
    ADD CONSTRAINT memory_classifications_pkey PRIMARY KEY (id);


--
-- Name: memory_tags memory_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_tags
    ADD CONSTRAINT memory_tags_pkey PRIMARY KEY (id);


--
-- Name: memory_taxonomy_categories memory_taxonomy_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_taxonomy_categories
    ADD CONSTRAINT memory_taxonomy_categories_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: npc_memories npc_memories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_memories
    ADD CONSTRAINT npc_memories_pkey PRIMARY KEY (id);


--
-- Name: npcs npcs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npcs
    ADD CONSTRAINT npcs_pkey PRIMARY KEY (id);


--
-- Name: photos photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.photos
    ADD CONSTRAINT photos_pkey PRIMARY KEY (id);


--
-- Name: plants plants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (user_id);


--
-- Name: rankings rankings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rankings
    ADD CONSTRAINT rankings_pkey PRIMARY KEY (user_id);


--
-- Name: recognitions recognitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recognitions
    ADD CONSTRAINT recognitions_pkey PRIMARY KEY (id);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: resonances resonances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resonances
    ADD CONSTRAINT resonances_pkey PRIMARY KEY (id);


--
-- Name: seeds seeds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seeds
    ADD CONSTRAINT seeds_pkey PRIMARY KEY (id);


--
-- Name: titles titles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_pkey PRIMARY KEY (id);


--
-- Name: tutorial_progress tutorial_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutorial_progress
    ADD CONSTRAINT tutorial_progress_pkey PRIMARY KEY (id);


--
-- Name: world_changes uk2epsvds02u1lbbql0wthoyku8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT uk2epsvds02u1lbbql0wthoyku8 UNIQUE (recognition_id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: world_decorations uk2v18fe6udk28iep6cicgmlsbo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_decorations
    ADD CONSTRAINT uk2v18fe6udk28iep6cicgmlsbo UNIQUE (character_id, decoration_type);


--
-- Name: memory_classification_tags uk38pd2bluw9o125glntv4uibs3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_tags
    ADD CONSTRAINT uk38pd2bluw9o125glntv4uibs3 UNIQUE (classification_id, tag_id);


--
-- Name: characters uk3r882i418xbsbcayej5g1gowx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT uk3r882i418xbsbcayej5g1gowx UNIQUE (user_id);


--
-- Name: world_terrain_tiles uk444ke5aesm1todr0dw91nkef2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_terrain_tiles
    ADD CONSTRAINT uk444ke5aesm1todr0dw91nkef2 UNIQUE (character_id, tile_x, tile_y);


--
-- Name: daily_penalties uk46gfv6dssoie6uwdp31cjb097; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_penalties
    ADD CONSTRAINT uk46gfv6dssoie6uwdp31cjb097 UNIQUE (user_id);


--
-- Name: inventories uk5ewb9ork9c3t673gv31m14rh2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT uk5ewb9ork9c3t673gv31m14rh2 UNIQUE (house_id);


--
-- Name: daily_missions uk6d0j1rb5hfgrhtmlx9b8utcp5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_missions
    ADD CONSTRAINT uk6d0j1rb5hfgrhtmlx9b8utcp5 UNIQUE (character_id, mission_date);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_titles uk6t7roohs9f01vy96mw1gltk5s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_titles
    ADD CONSTRAINT uk6t7roohs9f01vy96mw1gltk5s UNIQUE (character_id, title_id);


--
-- Name: npcs uk7ggj22y6qqb0v09idubg4k6f6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npcs
    ADD CONSTRAINT uk7ggj22y6qqb0v09idubg4k6f6 UNIQUE (region_id, npc_type);


--
-- Name: achievements uk9qqq83lafche8dr9o229kc9tg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT uk9qqq83lafche8dr9o229kc9tg UNIQUE (code);


--
-- Name: world_changes uk_world_changes_target_object; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT uk_world_changes_target_object UNIQUE (target_object_id);


--
-- Name: memory_taxonomy_categories ukanf4vln74hgq1f4m1o1weys7r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_taxonomy_categories
    ADD CONSTRAINT ukanf4vln74hgq1f4m1o1weys7r UNIQUE (code);


--
-- Name: collections ukaqkryyff4hg0aswelhvdo3e8j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT ukaqkryyff4hg0aswelhvdo3e8j UNIQUE (character_id, recognized_object);


--
-- Name: worlds ukbyomk8mlcilvp4melr8y4umd3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worlds
    ADD CONSTRAINT ukbyomk8mlcilvp4melr8y4umd3 UNIQUE (character_id);


--
-- Name: world_evolutions ukddvah4lkt7ekjswtblstss6et; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_evolutions
    ADD CONSTRAINT ukddvah4lkt7ekjswtblstss6et UNIQUE (character_id);


--
-- Name: village_changes ukdw2ntsnoo1o437c5dx8th8jnq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_changes
    ADD CONSTRAINT ukdw2ntsnoo1o437c5dx8th8jnq UNIQUE (character_id, change_type);


--
-- Name: user_achievements ukgcxfpeoi86h004rygcj8biuyc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT ukgcxfpeoi86h004rygcj8biuyc UNIQUE (character_id, achievement_id);


--
-- Name: world_player_positions ukgmh7nqm8wbm7ofougf05enys7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_player_positions
    ADD CONSTRAINT ukgmh7nqm8wbm7ofougf05enys7 UNIQUE (character_id);


--
-- Name: photos uki1atubrnrebcaugl0q8evgr39; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.photos
    ADD CONSTRAINT uki1atubrnrebcaugl0q8evgr39 UNIQUE (plant_id);


--
-- Name: regions uki63snboqd407fn32edpvrtc9e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT uki63snboqd407fn32edpvrtc9e UNIQUE (world_id, region_type);


--
-- Name: houses ukibw0efqqi53h4m8949k1s7pu2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT ukibw0efqqi53h4m8949k1s7pu2 UNIQUE (world_id);


--
-- Name: memory_classification_categories ukikqnm29elt7kedio0ewbty5ul; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_categories
    ADD CONSTRAINT ukikqnm29elt7kedio0ewbty5ul UNIQUE (classification_id, category_id);


--
-- Name: friends ukkfpr9vjrin0b2d6k5of006l9c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT ukkfpr9vjrin0b2d6k5of006l9c UNIQUE (requester_id, receiver_id);


--
-- Name: resonances ukmwadkg26yuhtbyuoycaekujps; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resonances
    ADD CONSTRAINT ukmwadkg26yuhtbyuoycaekujps UNIQUE (recognition_id);


--
-- Name: village_memories ukmyh25ymujoot77rxmx5tw3b8v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_memories
    ADD CONSTRAINT ukmyh25ymujoot77rxmx5tw3b8v UNIQUE (character_id, category);


--
-- Name: memory_tags uknjx606npaafu1cqvsuph3p20g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_tags
    ADD CONSTRAINT uknjx606npaafu1cqvsuph3p20g UNIQUE (code);


--
-- Name: titles ukp66yoxalyk0n7xgubadcbvw0f; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT ukp66yoxalyk0n7xgubadcbvw0f UNIQUE (code);


--
-- Name: seeds ukpnlbc0918k4fqmbf60an9hw10; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seeds
    ADD CONSTRAINT ukpnlbc0918k4fqmbf60an9hw10 UNIQUE (inventory_id, seed_type);


--
-- Name: village_theme_snapshots ukputc25ph2efm9onvjiw41gr6x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_theme_snapshots
    ADD CONSTRAINT ukputc25ph2efm9onvjiw41gr6x UNIQUE (character_id);


--
-- Name: recognitions ukpx28ftjxk9v0kv5qky4utjcfk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recognitions
    ADD CONSTRAINT ukpx28ftjxk9v0kv5qky4utjcfk UNIQUE (photo_id);


--
-- Name: character_statistics ukqdchiiem3uvcv3hfjlp6pdy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.character_statistics
    ADD CONSTRAINT ukqdchiiem3uvcv3hfjlp6pdy UNIQUE (character_id);


--
-- Name: npc_memories ukr79bd1j9qedrge00q05ryndo8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npc_memories
    ADD CONSTRAINT ukr79bd1j9qedrge00q05ryndo8 UNIQUE (character_id, npc_id);


--
-- Name: photos uks6i8bxtvdt0xiuihwld0apsot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.photos
    ADD CONSTRAINT uks6i8bxtvdt0xiuihwld0apsot UNIQUE (stored_file_name);


--
-- Name: tutorial_progress uksk3nd68b6fkyyhtbkj5oqe9sy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutorial_progress
    ADD CONSTRAINT uksk3nd68b6fkyyhtbkj5oqe9sy UNIQUE (character_id);


--
-- Name: user_achievements user_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (id);


--
-- Name: user_titles user_titles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_titles
    ADD CONSTRAINT user_titles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: village_changes village_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_changes
    ADD CONSTRAINT village_changes_pkey PRIMARY KEY (id);


--
-- Name: village_histories village_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_histories
    ADD CONSTRAINT village_histories_pkey PRIMARY KEY (id);


--
-- Name: village_memories village_memories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_memories
    ADD CONSTRAINT village_memories_pkey PRIMARY KEY (id);


--
-- Name: village_theme_snapshots village_theme_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_theme_snapshots
    ADD CONSTRAINT village_theme_snapshots_pkey PRIMARY KEY (id);


--
-- Name: world_changes world_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT world_changes_pkey PRIMARY KEY (id);


--
-- Name: world_decorations world_decorations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_decorations
    ADD CONSTRAINT world_decorations_pkey PRIMARY KEY (id);


--
-- Name: world_evolutions world_evolutions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_evolutions
    ADD CONSTRAINT world_evolutions_pkey PRIMARY KEY (id);


--
-- Name: world_placed_objects world_placed_objects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_placed_objects
    ADD CONSTRAINT world_placed_objects_pkey PRIMARY KEY (id);


--
-- Name: world_player_positions world_player_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_player_positions
    ADD CONSTRAINT world_player_positions_pkey PRIMARY KEY (id);


--
-- Name: world_terrain_tiles world_terrain_tiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_terrain_tiles
    ADD CONSTRAINT world_terrain_tiles_pkey PRIMARY KEY (id);


--
-- Name: worlds worlds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worlds
    ADD CONSTRAINT worlds_pkey PRIMARY KEY (id);


--
-- Name: idx_memory_classification_categories_category_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classification_categories_category_id ON public.memory_classification_categories USING btree (category_id);


--
-- Name: idx_memory_classification_categories_classification_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classification_categories_classification_id ON public.memory_classification_categories USING btree (classification_id);


--
-- Name: idx_memory_classification_tags_classification_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classification_tags_classification_id ON public.memory_classification_tags USING btree (classification_id);


--
-- Name: idx_memory_classification_tags_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classification_tags_tag_id ON public.memory_classification_tags USING btree (tag_id);


--
-- Name: idx_memory_classifications_photo_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classifications_photo_created_at ON public.memory_classifications USING btree (photo_id, created_at);


--
-- Name: idx_memory_classifications_primary_category_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classifications_primary_category_id ON public.memory_classifications USING btree (primary_category_id);


--
-- Name: idx_memory_classifications_recognition_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classifications_recognition_id ON public.memory_classifications USING btree (recognition_id);


--
-- Name: idx_memory_classifications_taxonomy_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_classifications_taxonomy_version ON public.memory_classifications USING btree (taxonomy_version);


--
-- Name: idx_memory_tags_active_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_tags_active_code ON public.memory_tags USING btree (active, code);


--
-- Name: idx_memory_tags_tag_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_tags_tag_type ON public.memory_tags USING btree (tag_type);


--
-- Name: idx_memory_tags_taxonomy_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_tags_taxonomy_version ON public.memory_tags USING btree (taxonomy_version);


--
-- Name: idx_memory_taxonomy_categories_active_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_taxonomy_categories_active_sort ON public.memory_taxonomy_categories USING btree (active, sort_order);


--
-- Name: idx_memory_taxonomy_categories_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_taxonomy_categories_parent_id ON public.memory_taxonomy_categories USING btree (parent_id);


--
-- Name: idx_memory_taxonomy_categories_taxonomy_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memory_taxonomy_categories_taxonomy_version ON public.memory_taxonomy_categories USING btree (taxonomy_version);


--
-- Name: idx_recognitions_planting_target_object_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recognitions_planting_target_object_id ON public.recognitions USING btree (planting_target_object_id);


--
-- Name: ux_memory_classifications_legacy_recognition; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_memory_classifications_legacy_recognition ON public.memory_classifications USING btree (recognition_id, provider, model_version, taxonomy_version) WHERE (recognition_id IS NOT NULL);


--
-- Name: tutorial_progress fk1blisnlr1kftqq4dmpu4tub5a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutorial_progress
    ADD CONSTRAINT fk1blisnlr1kftqq4dmpu4tub5a FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: worlds fk1pdcr9hxcj0602aiu95qly331; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worlds
    ADD CONSTRAINT fk1pdcr9hxcj0602aiu95qly331 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: memory_classification_categories fk1pya77inppln294c4tsna7did; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_categories
    ADD CONSTRAINT fk1pya77inppln294c4tsna7did FOREIGN KEY (classification_id) REFERENCES public.memory_classifications(id);


--
-- Name: npcs fk2124n157kmywm1i0wpwyw4yt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.npcs
    ADD CONSTRAINT fk2124n157kmywm1i0wpwyw4yt FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: characters fk27yx743bsnnsqplnjhk5yf224; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT fk27yx743bsnnsqplnjhk5yf224 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: memory_classifications fk2h36jm4l6qwwbwvwev1vqtbu5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classifications
    ADD CONSTRAINT fk2h36jm4l6qwwbwvwev1vqtbu5 FOREIGN KEY (primary_category_id) REFERENCES public.memory_taxonomy_categories(id);


--
-- Name: character_statistics fk2xekukmbwr2tnlaeo7sq1c436; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.character_statistics
    ADD CONSTRAINT fk2xekukmbwr2tnlaeo7sq1c436 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: profiles fk410q61iev7klncmpqfuo85ivh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_achievements fk4m0exrwfnvd37q6ieejp2g00y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fk4m0exrwfnvd37q6ieejp2g00y FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: memory_classifications fk4ye5vc71uj0u6qm9f5ouo58c5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classifications
    ADD CONSTRAINT fk4ye5vc71uj0u6qm9f5ouo58c5 FOREIGN KEY (photo_id) REFERENCES public.photos(id);


--
-- Name: friends fk5c5mwkpdeyhhbhulwujqhv4al; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT fk5c5mwkpdeyhhbhulwujqhv4al FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: inventories fk5hiccj86y5fans4xqljhm132n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT fk5hiccj86y5fans4xqljhm132n FOREIGN KEY (house_id) REFERENCES public.houses(id);


--
-- Name: friends fk5mwylmmw7ot92jog0004x3gn1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT fk5mwylmmw7ot92jog0004x3gn1 FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- Name: world_player_positions fk6acbaeqsnubs0lgancbvyy1ns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_player_positions
    ADD CONSTRAINT fk6acbaeqsnubs0lgancbvyy1ns FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: memory_classification_tags fk6hc5oay7xtouhvlpblh0yxw3b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_tags
    ADD CONSTRAINT fk6hc5oay7xtouhvlpblh0yxw3b FOREIGN KEY (tag_id) REFERENCES public.memory_tags(id);


--
-- Name: memory_classification_tags fk7dm29m7ti4oe3ok5nhwqi7ryc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_tags
    ADD CONSTRAINT fk7dm29m7ti4oe3ok5nhwqi7ryc FOREIGN KEY (classification_id) REFERENCES public.memory_classifications(id);


--
-- Name: village_histories fk86qmi90xl5r1m671fpgjtwpq4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_histories
    ADD CONSTRAINT fk86qmi90xl5r1m671fpgjtwpq4 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: cheers fk8cebdle9sus9pw6fioo0kotmq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cheers
    ADD CONSTRAINT fk8cebdle9sus9pw6fioo0kotmq FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: user_achievements fk8ipvec6cs8t3g8515thtlsxuf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fk8ipvec6cs8t3g8515thtlsxuf FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);


--
-- Name: world_changes fk8w0fylhg9a5cqi1drsxj82amt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT fk8w0fylhg9a5cqi1drsxj82amt FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: plants fk9lgvuw88f47yw4wdrn55cuk8p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT fk9lgvuw88f47yw4wdrn55cuk8p FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: recognitions fk_recognitions_planting_target_object; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recognitions
    ADD CONSTRAINT fk_recognitions_planting_target_object FOREIGN KEY (planting_target_object_id) REFERENCES public.world_placed_objects(id) ON DELETE RESTRICT;


--
-- Name: world_changes fk_world_changes_target_object; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT fk_world_changes_target_object FOREIGN KEY (target_object_id) REFERENCES public.world_placed_objects(id) ON DELETE RESTRICT;


--
-- Name: daily_missions fkai24li3y2uegv9kr2o6yo9pob; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_missions
    ADD CONSTRAINT fkai24li3y2uegv9kr2o6yo9pob FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: collections fkaynlndi9ddu3ptyb48ncdm2e7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT fkaynlndi9ddu3ptyb48ncdm2e7 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: resonances fkbyk1ce5dy8xuhjjetetjjl754; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resonances
    ADD CONSTRAINT fkbyk1ce5dy8xuhjjetetjjl754 FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id);


--
-- Name: rankings fkcup4ei1jmensgunlbncpb5rnv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rankings
    ADD CONSTRAINT fkcup4ei1jmensgunlbncpb5rnv FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: village_memories fkd2rp109k73xin03mu1f1he97t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_memories
    ADD CONSTRAINT fkd2rp109k73xin03mu1f1he97t FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: world_evolutions fke8b8it6wltm0x9ucbm0ly4gqf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_evolutions
    ADD CONSTRAINT fke8b8it6wltm0x9ucbm0ly4gqf FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: world_terrain_tiles fke8ylv8ey1wikc2njfm3a4yhb1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_terrain_tiles
    ADD CONSTRAINT fke8ylv8ey1wikc2njfm3a4yhb1 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: houses fkegno4wgvr8jrckrsp08fnkccg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT fkegno4wgvr8jrckrsp08fnkccg FOREIGN KEY (world_id) REFERENCES public.worlds(id);


--
-- Name: village_theme_snapshots fkemmcrc8suqj3ski1tthopparj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_theme_snapshots
    ADD CONSTRAINT fkemmcrc8suqj3ski1tthopparj FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: memory_classification_categories fkgdc1qua6wy5r7xf5rwxpvdt4c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classification_categories
    ADD CONSTRAINT fkgdc1qua6wy5r7xf5rwxpvdt4c FOREIGN KEY (category_id) REFERENCES public.memory_taxonomy_categories(id);


--
-- Name: village_changes fkgrbtk7278xgesc9f5k5vg1hck; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.village_changes
    ADD CONSTRAINT fkgrbtk7278xgesc9f5k5vg1hck FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: memory_taxonomy_categories fki519adi9qk4k70kug5eaxarb7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_taxonomy_categories
    ADD CONSTRAINT fki519adi9qk4k70kug5eaxarb7 FOREIGN KEY (parent_id) REFERENCES public.memory_taxonomy_categories(id);


--
-- Name: world_changes fkj15ar1sa6lagj31292pn5j43u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_changes
    ADD CONSTRAINT fkj15ar1sa6lagj31292pn5j43u FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id);


--
-- Name: recognitions fkjdichcej5rg4iqp6x3cqix0jn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recognitions
    ADD CONSTRAINT fkjdichcej5rg4iqp6x3cqix0jn FOREIGN KEY (photo_id) REFERENCES public.photos(id);


--
-- Name: plants fkjgkvok4d234gu9gucd0wvuogx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT fkjgkvok4d234gu9gucd0wvuogx FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: world_placed_objects fkkqsx2ibrm9flq3puvf3dyrsmd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_placed_objects
    ADD CONSTRAINT fkkqsx2ibrm9flq3puvf3dyrsmd FOREIGN KEY (world_change_id) REFERENCES public.world_changes(id);


--
-- Name: photos fkl12qswht99rhb7g0n6ikr2dex; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.photos
    ADD CONSTRAINT fkl12qswht99rhb7g0n6ikr2dex FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: photos fklseja2ahb5b5p7r1p7n0sncbd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.photos
    ADD CONSTRAINT fklseja2ahb5b5p7r1p7n0sncbd FOREIGN KEY (plant_id) REFERENCES public.plants(id);


--
-- Name: user_titles fkmk90gv5drr0eeqtsf5egimq5n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_titles
    ADD CONSTRAINT fkmk90gv5drr0eeqtsf5egimq5n FOREIGN KEY (title_id) REFERENCES public.titles(id);


--
-- Name: resonances fkmqyhwgvg7woec8tkhlayn7p32; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resonances
    ADD CONSTRAINT fkmqyhwgvg7woec8tkhlayn7p32 FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: regions fkn9u923h50yu5f6u9eganuxmkw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT fkn9u923h50yu5f6u9eganuxmkw FOREIGN KEY (world_id) REFERENCES public.worlds(id);


--
-- Name: memory_classifications fknf1wgaelgse7ak0sgo5t8di0k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_classifications
    ADD CONSTRAINT fknf1wgaelgse7ak0sgo5t8di0k FOREIGN KEY (recognition_id) REFERENCES public.recognitions(id);


--
-- Name: world_decorations fknpdtuj84etoh0mpl3d0s23lah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.world_decorations
    ADD CONSTRAINT fknpdtuj84etoh0mpl3d0s23lah FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: cheers fkosxm3986obrhfkb3ndeax9752; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cheers
    ADD CONSTRAINT fkosxm3986obrhfkb3ndeax9752 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: daily_penalties fkp80nlx0ffwctef12t01a6oyaa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_penalties
    ADD CONSTRAINT fkp80nlx0ffwctef12t01a6oyaa FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: evolution_histories fkpnr98sg06lp2q5p21x737pj3e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evolution_histories
    ADD CONSTRAINT fkpnr98sg06lp2q5p21x737pj3e FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: user_titles fkr1p9br77phv1mvvs1ql2e1ntt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_titles
    ADD CONSTRAINT fkr1p9br77phv1mvvs1ql2e1ntt FOREIGN KEY (character_id) REFERENCES public.characters(id);


--
-- Name: island_visits fks7yqpishd8ytptoc8i9aqutt7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.island_visits
    ADD CONSTRAINT fks7yqpishd8ytptoc8i9aqutt7 FOREIGN KEY (visitor_id) REFERENCES public.users(id);


--
-- Name: seeds fksh02yifcshfhdh9f95b3ir82q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seeds
    ADD CONSTRAINT fksh02yifcshfhdh9f95b3ir82q FOREIGN KEY (inventory_id) REFERENCES public.inventories(id);


--
-- Name: island_visits fksiiw8lctcnng8ybismqik9k9d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.island_visits
    ADD CONSTRAINT fksiiw8lctcnng8ybismqik9k9d FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--
