CREATE TABLE IF NOT EXISTS memory_taxonomy_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    category_type VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    taxonomy_version VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_memory_taxonomy_categories_code UNIQUE (code),
    CONSTRAINT fk_memory_taxonomy_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES memory_taxonomy_categories (id)
);

CREATE INDEX IF NOT EXISTS idx_memory_taxonomy_categories_active_sort
    ON memory_taxonomy_categories (active, sort_order);

CREATE INDEX IF NOT EXISTS idx_memory_taxonomy_categories_parent_id
    ON memory_taxonomy_categories (parent_id);

CREATE INDEX IF NOT EXISTS idx_memory_taxonomy_categories_taxonomy_version
    ON memory_taxonomy_categories (taxonomy_version);

CREATE TABLE IF NOT EXISTS memory_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    tag_type VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL,
    taxonomy_version VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_memory_tags_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_memory_tags_active_code
    ON memory_tags (active, code);

CREATE INDEX IF NOT EXISTS idx_memory_tags_tag_type
    ON memory_tags (tag_type);

CREATE INDEX IF NOT EXISTS idx_memory_tags_taxonomy_version
    ON memory_tags (taxonomy_version);
