CREATE TABLE IF NOT EXISTS memory_classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL,
    recognition_id BIGINT,
    primary_category_id BIGINT,
    observation JSONB,
    summary VARCHAR(500),
    confidence NUMERIC(5, 4),
    provider VARCHAR(40) NOT NULL,
    model_version VARCHAR(100),
    taxonomy_version VARCHAR(20) NOT NULL,
    fallback BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_memory_classifications_photo
        FOREIGN KEY (photo_id)
        REFERENCES photos (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_memory_classifications_recognition
        FOREIGN KEY (recognition_id)
        REFERENCES recognitions (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_memory_classifications_primary_category
        FOREIGN KEY (primary_category_id)
        REFERENCES memory_taxonomy_categories (id),
    CONSTRAINT chk_memory_classifications_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX IF NOT EXISTS idx_memory_classifications_photo_created_at
    ON memory_classifications (photo_id, created_at);

CREATE INDEX IF NOT EXISTS idx_memory_classifications_recognition_id
    ON memory_classifications (recognition_id);

CREATE INDEX IF NOT EXISTS idx_memory_classifications_primary_category_id
    ON memory_classifications (primary_category_id);

CREATE INDEX IF NOT EXISTS idx_memory_classifications_taxonomy_version
    ON memory_classifications (taxonomy_version);

CREATE TABLE IF NOT EXISTS memory_classification_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    confidence NUMERIC(5, 4),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_memory_classification_categories_classification
        FOREIGN KEY (classification_id)
        REFERENCES memory_classifications (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_memory_classification_categories_category
        FOREIGN KEY (category_id)
        REFERENCES memory_taxonomy_categories (id),
    CONSTRAINT uk_memory_classification_categories_classification_category
        UNIQUE (classification_id, category_id),
    CONSTRAINT chk_memory_classification_categories_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX IF NOT EXISTS idx_memory_classification_categories_classification_id
    ON memory_classification_categories (classification_id);

CREATE INDEX IF NOT EXISTS idx_memory_classification_categories_category_id
    ON memory_classification_categories (category_id);

CREATE TABLE IF NOT EXISTS memory_classification_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    confidence NUMERIC(5, 4),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_memory_classification_tags_classification
        FOREIGN KEY (classification_id)
        REFERENCES memory_classifications (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_memory_classification_tags_tag
        FOREIGN KEY (tag_id)
        REFERENCES memory_tags (id),
    CONSTRAINT uk_memory_classification_tags_classification_tag
        UNIQUE (classification_id, tag_id),
    CONSTRAINT chk_memory_classification_tags_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX IF NOT EXISTS idx_memory_classification_tags_classification_id
    ON memory_classification_tags (classification_id);

CREATE INDEX IF NOT EXISTS idx_memory_classification_tags_tag_id
    ON memory_classification_tags (tag_id);
